version: '3.8'

services:
  weatherwave-app:
    build: .
    ports:
      - "3000:80"     # Frontend (nginx)
      - "8000:8000"   # Backend API (Django)
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=weatherwave_project.settings
    volumes:
      - ./backend:/app/backend          # Hot reload for backend development
      - ./ml:/app/ml                    # ML models and data
    restart: unless-stopped

  # Optional: Add a development override
  weatherwave-dev:
    build: .
    ports:
      - "5173:80"     # Frontend on Vite's default port
      - "8001:8000"   # Backend on alternative port
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=weatherwave_project.settings
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend        # Frontend source for development
      - ./ml:/app/ml
    profiles:
      - dev
