# Generated by Django 5.2.1 on 2025-06-29 13:41

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favourite", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favourite",
            options={"ordering": ["-added_at"]},
        ),
        migrations.RenameField(
            model_name="favourite",
            old_name="city",
            new_name="district_name",
        ),
        migrations.AddField(
            model_name="favourite",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together={("user", "district_name")},
        ),
    ]
